package com.project.api.projectapi;
///////////////////////////////////////////////////////////////////////////////////////////////////////
//  FILE : ApiAppilcation.java
//  AUTHOR : Auto-Generated by using https://start.spring.io/
//  DESCRIPTION: Is the primary file for the application, run this to launch springboot
//               DO NOT change this file unless necessary
//
///////////////////////////////////////////////////////////////////////////////////////////////////////

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class ApiApplication {
	public static void main(String[] args) {
		SpringApplication.run(ApiApplication.class, args);
	}
}